version: '2'
services:
  mapd-core:
    image: ${MAPD_IMAGE}
    restart: always
    entrypoint: ["mapd_server", "--http-port", "9090", "-p", "9091", "--data", "/data/mapd-data-00", "--read-only", "--db-query-list", "/data/warm-up.sql"]
    volumes:
      - ./data:/data
  mapd-api:
    image: shusson/mapd-api:1.3.3
    restart: always
    entrypoint: ["/go/bin/app"]
    command: ["-url", "http://mapd-core:9090", "-redis", "cache:6379"]
    ports:
      - 80:4000
    depends_on:
      - mapd-core
  cache:
    image: shusson/lru-cache:1.1
    restart: always
    volumes:
      - ./cache:/data
